---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: Deploy and Test
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: ''
    type: text
  - name: APP_URL
    value: ''
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: Sauce-testStageSetsURL
    script: |
      #!/bin/bash
      cf push "${CF_APP}"

      export CF_APP_NAME="$CF_APP"

      # view logs
      #cf logs "${CF_APP}" --recent
  - name: Test
    type: tester
    extension_id: ibm.devops.services.pipeline.saucelabs
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    ACCESS: Access Key here
    DL_ASSETS: 'true'
    SELECT_CMD: npm test
    USER_ID: Sauce user ID here
    COMMAND: '#!/bin/bash'
